package com.example.spring.user.service;

import com.example.spring.user.model.User;
import com.example.spring.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class UserService {

    private UserRepository userRepository;

    @Autowired  // This means to get the bean called noteRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public List<User> findAll() {
        return userRepository.findAll();
    }

    public Optional<User> findById(Long id) {
        return userRepository.findById(id);
    }

    public User save(User note) {
        return userRepository.save(note);
    }

    public void deleteById(Long id) {
        userRepository.deleteById(id);
    }
}
